version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:15"
  - package-ecosystem: "npm"
    directory: "/reposilite-frontend"
    schedule:
      interval: "daily"
      time: "16:15"
