language: java
sudo: true

jdk:
- openjdk8

script:
  - mvn test jacoco:report-aggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn coveralls:report

notifications:
  email: false
